create database CONTROLE_GASTOS_DB;
use CONTROLE_GASTOS_DB;
create table ContaDeLuz
(
    NUMERO_LEITURA BIGINT NOT NULL,
    DATA_LEITURA DATE NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    KW_GASTO_MES DECIMAL(11,2) NOT NULL,
    VALOR DECIMAL(11,2) NOT NULL,
    MEDIA_CONSUMO DECIMAL(11,2) NOT NULL,
    CONSTRAINT PK_NUMERO_LEITURA PRIMARY KEY(NUMERO_LEITURA)
);